export const ACTIONS = {
  LOGIN: 'LOGIN', 
  LOGOUT: 'LOGOUT',
  ADD_ASSET: 'ADD_ASSET', 
  DELETE_ASSET: 'DELETE_ASSET',
  ASSIGN_ASSET: 'ASSIGN_ASSET', 
  RETURN_ASSET: 'RETURN_ASSET',
  ADD_EMPLOYEE: 'ADD_EMPLOYEE', 
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
  ADD_TOAST: 'ADD_TOAST', 
  REMOVE_TOAST: 'REMOVE_TOAST',
};